name: Backend CD (Deploy to AWS EC2)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to AWS EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/backend
            git pull origin main
            chmod +x gradlew
            ./gradlew build --stacktrace
            pkill -f 'java -jar' || true
            nohup java -jar build/libs/*.jar > log.txt 2>&1 &
